### ISSUE TITLE
Unable to build Lineage for Capri

### ISSUE THREAD

**Issue by michaelmcallister** [moto-sm6115/device_motorola_sm4250-common#1]
Hello,

I'm attempting to build LineageOS for capri (motorola g10) but I'm not having much luck, is it expected to work?

This is my local_manifest
```
<?xml version="1.0" encoding="UTF-8"?>

<manifest>
    <remote name="vendor"
            fetch="https://github.com"
            revision="lineage-18.1" />

    <remote name="device"
            fetch="https://github.com"
            revision="lineage-18.1"/>

    <remote name="kernel"
            fetch="https://github.com"
            revision="refs/tags/MMI-RRB31.Q1-3-48-2"/>

    <!--Device Trees-->
    <project path="device/motorola/sm4250-common" name="moto-sm6115/device_motorola_sm4250-common" remote="device" />

    <!--Kernel-->
    <project path="kernel/motorola/sm6115" name="MotorolaMobilityLLC/kernel-msm" remote="kernel" />

    <!-- Vendor folders -->
    <project path="vendor/motorola" name="ferhzzoma/vendor_motorola" remote="vendor" />
</manifest>
```

Any pointers in the right direction would be much appreciated.

**Comment by Deivid21** [comment]
@michaelmcallister Que wea

**Comment by kytoaq** [comment]
Hi there. This repository contains the instructions for building LineageOS. You need a proper kernel, because Motorola publishes the kernel without personal modifications to start editing. This repository is currently on WIP and you might get some errors during build. You can edit it if you need any other modifications. I suggest a fork.

— Signed-off-by: @kytoaq <kytoaq@gmail.com>—

**Comment by akoerner** [comment]
> Hello,
> 
> I'm attempting to build LineageOS for capri (motorola g10) but I'm not having much luck, is it expected to work?
> 
> This is my local_manifest
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <manifest>
>     <remote name="vendor"
>             fetch="https://github.com"
>             revision="lineage-18.1" />
> 
>     <remote name="device"
>             fetch="https://github.com"
>             revision="lineage-18.1"/>
> 
>     <remote name="kernel"
>             fetch="https://github.com"
>             revision="refs/tags/MMI-RRB31.Q1-3-48-2"/>
> 
>     
>     <project path="device/motorola/sm4250-common" name="moto-sm6115/device_motorola_sm4250-common" remote="device" />
> 
>     
>     <project path="kernel/motorola/sm6115" name="MotorolaMobilityLLC/kernel-msm" remote="kernel" />
> 
>     
>     <project path="vendor/motorola" name="ferhzzoma/vendor_motorola" remote="vendor" />
> </manifest>
> ```
> 
> Any pointers in the right direction would be much appreciated.

did you have any luck on this or did you end up giving up?
